### ISSUE TITLE
Pip install error

### ISSUE THREAD

**Issue by sanbales** [Yomguithereal/ipysigma#3]
https://github.com/Yomguithereal/ipysigma/blob/6f92e6248387106a988c728fb0df6615ea34d5c3/setup.py#L139

Looks like it should be:

`        ('etc/jupyter/nbconfig/notebook.d' ,['ipysigma.json'])`

Trying to pip install on Windows (Win10) gives the following error:

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sb282\AppData\Local\Temp\pip-install-u4fzz9r4\ipysigma\setup.py", line 177, in <module>
        setup(**setup_args)
      File "C:\conda\envs\jpr\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\conda\envs\jpr\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\conda\envs\jpr\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\conda\envs\jpr\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\conda\envs\jpr\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\conda\envs\jpr\lib\distutils\command\install.py", line 557, in run
        self.run_command(cmd_name)
      File "C:\conda\envs\jpr\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\conda\envs\jpr\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\conda\envs\jpr\lib\distutils\command\install_data.py", line 56, in run
        dir = convert_path(f[0])
      File "C:\conda\envs\jpr\lib\distutils\util.py", line 127, in convert_path
        raise ValueError("path '%s' cannot end with '/'" % pathname)
    ValueError: path 'etc/jupyter/nbconfig/notebook.d/' cannot end with '/'
```

**Comment by Yomguithereal** [comment]
Hello @sanbales. Maybe so, this is coming from jupyter's templates, but they may be wrong indeed. Does this fix the issue for you? If so, do you want to open a PR fixing the issue?

**Comment by sanbales** [comment]
Will do.
